name: Merge dev dans main

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types:
      - closed

permissions:
  contents: write

jobs:
  merge-to-main:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into master
        run: |
          git fetch origin master
          git checkout master
          git merge origin/dev -m "Automated merge from dev to master [skip ci]"
          git push origin master
